on:
  push:
    tags:
    - 'v*'

name: Create release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set vars
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          echo ::set-output name=repo-name::${GITHUB_REPOSITORY#*/}
      - name: Compress Dashboards
        run: |
          zip --junk-paths dashboards-${{ steps.vars.outputs.tag }}.zip ./kibana/*.ndjson
          tar -zcf dashboards-${{ steps.vars.outputs.tag }}.tar.gz ./kibana/*.ndjson
      - name: Compress Source code
        run: |
          zip --junk-paths ${{ steps.vars.outputs.repo-name }}-${{ steps.vars.outputs.tag }}.zip *
          tar -zcf ${{ steps.vars.outputs.repo-name }}-${{ steps.vars.outputs.tag }}.tar.gz *
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Zip Dashboards
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dashboards-${{ steps.vars.outputs.tag }}.zip
          asset_name: dashboards-${{ steps.vars.outputs.tag }}.zip
          asset_content_type: application/zip
      - name: Upload tar.gz Dashboards
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dashboards-${{ steps.vars.outputs.tag }}.tar.gz
          asset_name: dashboards-${{ steps.vars.outputs.tag }}.tar.gz
          asset_content_type: application/tar+gzip
      - name: Upload Zip Source Code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.vars.outputs.repo-name }}-${{ steps.vars.outputs.tag }}.zip
          asset_name: Source Code (zip)
          asset_content_type: application/zip
      - name: Upload tar.gz Source Code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.vars.outputs.repo-name }}-${{ steps.vars.outputs.tag }}.tar.gz
          asset_name: Source Code (tar.gz)
          asset_content_type: application/tar+gzip
